# Generated by Django 3.2.6 on 2021-08-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(max_length=6, unique=True, verbose_name='Event Code')),
                ('day', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Day')),
                ('start', models.CharField(max_length=5, verbose_name='Start')),
                ('end', models.CharField(max_length=5, verbose_name='Start')),
                ('title', models.CharField(max_length=256, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Event Banner')),
                ('seats', models.IntegerField(default=0, verbose_name='Event Seats')),
                ('max_seats', models.IntegerField(default=0, verbose_name='Maximum Event Seats')),
                ('category', models.CharField(choices=[('C', 'Cultural'), ('T', 'Technical'), ('F', 'Fun')], max_length=1, verbose_name='Category')),
                ('is_seminar', models.BooleanField(default=False, verbose_name='Is Evenet a Seminar')),
                ('team_size', models.IntegerField(default=1, verbose_name='Team Size')),
                ('is_team_size_strict', models.BooleanField(verbose_name='Is Team Size Strict')),
                ('entry_fee', models.IntegerField(verbose_name='Entry Fee')),
                ('prize_money', models.TextField(verbose_name='Prize Money JSON')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=6, unique=True, verbose_name='Participation Code')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
