# Generated by Django 3.2.6 on 2021-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_is_seminar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(max_length=5, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Event Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(max_length=5, verbose_name='Start Time'),
        ),
    ]
