# Generated by Django 3.2.6 on 2021-08-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210806_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
