# Generated by Django 3.2.6 on 2021-08-07 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Event Code'),
        ),
    ]
