# Generated by Django 3.2.6 on 2021-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('C', 'Cultural'), ('S', 'Sports')], max_length=1, verbose_name='Category'),
        ),
    ]
