# Generated by Django 3.2.6 on 2021-08-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('roll_no', models.IntegerField(unique=True, verbose_name='Roll Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('department', models.CharField(choices=[('COMP', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('MECH', 'Mechanical'), ('ELEC', 'Electrical'), ('OTHER', 'Other')], max_length=10, verbose_name='Department')),
                ('semester', models.SmallIntegerField(verbose_name='Semester')),
                ('money_owed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Money Owed')),
                ('has_filled_profile', models.BooleanField(default=False, verbose_name='Has Filled Profile')),
                ('college_name', models.CharField(blank=True, max_length=500, verbose_name='College Name')),
                ('phone_no', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(max_length=6, unique=True, verbose_name='Team Code')),
                ('team_name', models.CharField(max_length=256, verbose_name='Team Name')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
