# Generated by Django 3.2.6 on 2021-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"1": false, "2": false, "3": false, "C": 0, "S": 0}', verbose_name='Criteria JSON'),
        ),
    ]
