# Generated by Django 3.2.6 on 2021-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"C": false, "T": false, "F": false, "1": false, "2": false, "3": false}', verbose_name='Criteria JSON'),
        ),
    ]
