# Generated by Django 3.2.6 on 2021-08-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210812_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('COMP', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('MECH', 'Mechanical'), ('ELEC', 'Electrical'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
    ]
