# Generated by Django 3.2.6 on 2021-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210812_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
