# Generated by Django 3.2.6 on 2021-08-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_participation'),
        ('users', '0003_user_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event'),
            preserve_default=False,
        ),
    ]
