# Generated by Django 3.2.6 on 2021-08-07 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Team Code'),
        ),
    ]
