# Generated by Django 3.2.6 on 2021-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.TextField(default='[]', verbose_name='DONT FILL THIS'),
        ),
    ]
