# Generated by Django 3.2.6 on 2021-08-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='team',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Transactions Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='criteria',
            field=models.TextField(default='{"1": false, "2": false, "3": false}', verbose_name='Criteria JSON'),
        ),
    ]
