# Generated by Django 3.2.6 on 2021-08-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
