# Generated by Django 3.2.6 on 2021-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_no_verified',
            field=models.BooleanField(default=False, verbose_name='Is Phone Number Verified'),
        ),
    ]
