# Generated by Django 3.2.6 on 2021-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210813_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.TextField(default='[]', verbose_name='Cart JSON'),
        ),
    ]
